### ISSUE TITLE
When nosqlunit-mongodb 0.8.2 will be released 

### ISSUE THREAD

**Issue by suhotskiy** [lordofthejars/nosql-unit#153]
When nosqlunit-mongodb 0.8.2 will be released

**Comment by lordofthejars** [comment]
Hi I have a problem with the Neo4J integration. Basically because Neo4j 2 does not have root element all the logic used to compare if two graphs are the same or not, doesn't work properly. I would like to fix it and then release butI have no time to investigate the problem :( 

You can see if you run this test https://github.com/lordofthejars/nosql-unit/blob/master/nosqlunit-demo/src/test/java/com/lordofthejars/nosqlunit/demo/neo4j/WhenNeoFriendsAreRequired.java

**Comment by lordofthejars** [comment]
Stay tuned. Maybe this weekend I will have time to release a new version :dancer:

**Comment by lordofthejars** [comment]
Released :)
